version: "3.8"
services:
    db:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=localhost
            - ALLOWED_HOSTS=127.0.0.1, localhost

        ports:
            - "5432"

    library-site:
        build:
            context: .
            target: library_site
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: -c "pipenv run start-dev"
        environment:
            - DEBUG
            - DJANGO_SECRET_KEY
            - ALLOWED_HOSTS
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - DEBUG_HOST
            - ALLOWED_HOSTS=127.0.0.1, localhost
        restart: "no"
        volumes:
            - .:/code
volumes: 
    postgres_data:
