version: "3.8"
services:
    db:
        image: postgres:12
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_HOST_AUTH_METHOD=trust

        ports:
        - "5432:5432"

        
    library-site:
        build:
            context: .
            target: library_site
        ports:
            - "8000:8000"
        depends_on:
            - db 
        command: -c "pipenv run start-dev"
        environment:
            - DEBUG
            - DJANGO_SECRET_KEY
            - ALLOWED_HOSTS
            - POSTGRES_DB
            - POSTGRES_HOST
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - DEBUG_HOST
        restart: "no"
        volumes:
            - .:/code
volumes: 
    postgres_data:
